# Vertices for 15" x 12" file drawer
v dv0 =
	p 0 0 .5
v dv1 =
	p 0 0 11.5
v dv2 =
	p 15 0 11.5
v dv3 =
	p 15 0 0.5
v dv4 =
	p 5 0 11.5
v dv5 =
	p 5 0 9
v dv6 =
	p 5 0 6.5
v dv7 =
	p 10 0 6.5
v dv8 =
	p 10 0 9
v dv0m =
	p 0 -.5 .5
	n -1 0 0
v dv1m =
	p 0 -.5 11.5
	n -1 0 0
v dv2m =
	p 15 -.5 11.5
	n 1 0 0
v dv3m =
	p 15 -.5 .5
	n 1 0 0
v dv0b =
	p 0 -1 .5
v dv1b =
	p 0 -1 11.5
v dv2b =
	p 15 -1 11.5
v dv3b =
	p 15 -1 .5
v dp0 =
	p 0 -1.1 0
v dp1 =
	p 0 -1.1 12
v dp2 =
	p 15 -1.1 12
v dp3 =
	p 15 -1.1 0
# Handle vertices:
v hv0 = dv6
v hv1 =
	p 5 0 6.7
v hv2 =
	p 5 -.75 6.5
v hv3 =
	p 5 -.75 9
v hv4 =
	p 5 0 8.25
v hv5 = dv5
v hv6 = dv8
v hv7 =
	p 10 0 8.25
v hv8 =
	p 10 -.75 9
v hv9 =
	p 10 -.75 6.5
v hv10 =
	p 10 0 6.7
v hv11 = dv7
