# Vertices for 15" x 12" file drawer
v dv0 =
	p 0 0 .5
v dv1 =
	p 0 0 8
v dv2 =
	p 15 0 8
v dv3 =
	p 15 0 0.5
v dv4 =
	p 5 0 8
v dv5 =
	p 5 0 5.5
v dv6 =
	p 5 0 3
v dv7 =
	p 10 0 3
v dv8 =
	p 10 0 5.5
v dv0m =
	p 0 -.5 .5
	n -1 0 0
v dv1m =
	p 0 -.5 8
	n -1 0 0
v dv2m =
	p 15 -.5 8
	n 1 0 0
v dv3m =
	p 15 -.5 .5
	n 1 0 0
v dv0b =
	p 0 -1 .5
v dv1b =
	p 0 -1 8
v dv2b =
	p 15 -1 8
v dv3b =
	p 15 -1 .5
v dp0 =
	p 0 -1.1 0
v dp1 =
	p 0 -1.1 8.5
v dp2 =
	p 15 -1.1 8.5
v dp3 =
	p 15 -1.1 0
# Handle vertices:
v hv0 = dv6
v hv1 =
	p 5 0 3.2
v hv2 =
	p 5 -.75 3
v hv3 =
	p 5 -.75 5.5
v hv4 =
	p 5 0 4.75
v hv5 = dv5
v hv6 = dv8
v hv7 =
	p 10 0 4.75
v hv8 =
	p 10 -.75 5.5
v hv9 =
	p 10 -.75 3
v hv10 =
	p 10 0 3.2
v hv11 = dv7
